# Generated by Django 4.2.6 on 2023-10-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TvShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Укажите название фильма')),
                ('description', models.TextField(verbose_name='Укажите описание фильма')),
                ('image', models.ImageField(upload_to='cinema/', verbose_name='Загрузите фото')),
                ('genre', models.CharField(choices=[('Хоррор', 'Хоррор'), ('Комедия', 'Комедия'), ('Фантастика', 'Фантастика'), ('Драмма', 'Драмма'), ('Боевик', 'Боевик')], max_length=100, verbose_name='Укажите жанр')),
                ('director', models.CharField(max_length=100, verbose_name='Укажите режисера')),
                ('cost', models.PositiveIntegerField(verbose_name='Укажите цену')),
                ('trailer', models.URLField(blank=True, verbose_name='Укажите трейлер')),
            ],
        ),
    ]
